name: Build Docker Image

on:
  push:
    branches: [ main, master ]  # 你自己需要的分支
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: PetitePluie-255/file-transfer-go           # 你可以改成任何本地镜像名

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Run build script
      run: bash ./build-fullstack.sh

    - name: List dist files
      run: ls -lh dist/

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile      # 如有不同路径请修改
        push: false                            # 关键参数，不推送
        tags: ${{ env.DOCKER_IMAGE_NAME }}:latest
        build-args: |
          BINARY=dist/file-transfer-server-linux-amd64

    - name: Save Docker image to tar file
      run: docker save -o file-transfer-server.tar mytest/image:latest

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-tar
        path: file-transfer-server.tar
